// create blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "How to test backend",
    "author": "Alice",
    "url":   "baergsdfvxzcvffhhtr.com/how-to-test-backend",
    "likes": "100"
}